# Nombre del workflow que aparecerá en la pestaña "Actions" de GitHub.
name: CI de Pruebas con Playwright y Docker

# Define cuándo se debe ejecutar este workflow.
on:
  push:
    branches: [main]
  workflow_dispatch:

# Define los trabajos (jobs) que se ejecutarán.
jobs:
  build-and-test:
    # El tipo de máquina virtual en la que se ejecutará el job.
    runs-on: ubuntu-latest

    # La secuencia de pasos que ejecutará el job.
    steps:
      # Paso 1: Checkout del código del repositorio.
      - name: Checkout del código
        uses: actions/checkout@v4

      # Paso 2: Construir la imagen de Docker.
      - name: Construir la imagen de Docker
        run: docker build -t express_qa_v1 .

      # Paso 3: Ejecutar las pruebas dentro del contenedor Docker.
      # Le damos un ID a este paso para poder referenciar su resultado (éxito o fallo).
      # 'continue-on-error: true' es CRUCIAL para que los siguientes pasos se ejecuten incluso si las pruebas fallan.
      - name: Ejecutar pruebas y capturar resultado
        id: run-tests
        continue-on-error: true
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/playwright-report:/app/playwright-report \
            -v ${{ github.workspace }}/test-results:/app/test-results \
            express_qa_v1

      # Paso 4: Subir el reporte HTML de Playwright.
      # 'if: always()' asegura que este paso se ejecute siempre, sin importar el resultado del paso anterior.
      - name: Subir reporte de Playwright
        if: always()
        uses: actions/upload-artifact@v4
        with:
          # El nombre que tendrá el artefacto descargable.
          name: playwright-report
          # La ruta de la carpeta que queremos subir.
          path: playwright-report/
          # Por cuántos días se guardará el artefacto.
          retention-days: 7

      # Paso 5: Subir los artefactos de fallo (si los hubo).
      # 'if: steps.run-tests.outcome == 'failure'' se ejecuta solo si el paso con id 'run-tests' falló.
      - name: Subir artefactos de fallo (si los tests fallaron)
        if: steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-failure-artifacts
          path: test-results/
          retention-days: 7

      # Paso 6: Verificar el resultado de las pruebas y hacer que el workflow falle si es necesario.
      # Este paso es la "alarma" final. Si el paso de tests falló, este paso hará que todo el workflow falle.
      - name: Verificar el resultado de las pruebas
        if: steps.run-tests.outcome == 'failure'
        run: |
          echo "La ejecución de pruebas ha fallado."
          exit 1
